"""add manual session plan table

Revision ID: 42b8948b2da4
Revises: 9adcb4247905
Create Date: 2026-04-30 10:15:07.185312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42b8948b2da4'
down_revision = '9adcb4247905'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manual_session_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manual_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=30), nullable=True),
    sa.Column('session_number', sa.Integer(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('steam_area_focus', sa.String(length=200), nullable=True),
    sa.Column('transversality', sa.String(length=200), nullable=True),
    sa.Column('topic', sa.String(length=200), nullable=True),
    sa.Column('activity_detail', sa.Text(), nullable=True),
    sa.Column('resources', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['manual_id'], ['project_manual.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manual_session_plan')
    # ### end Alembic commands ###
