"""add project manuals weekly plans manual rubrics

Revision ID: 9adcb4247905
Revises: 9f1d2c3b4a5e
Create Date: 2026-04-30 09:54:17.899968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9adcb4247905'
down_revision = '9f1d2c3b4a5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_manual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('grade_level', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('iframe_url', sa.String(length=500), nullable=True),
    sa.Column('content_markdown', sa.Text(), nullable=True),
    sa.Column('estimated_sessions', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manual_rubric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manual_id', sa.Integer(), nullable=False),
    sa.Column('bank_item_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('dimension', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('level_4', sa.Text(), nullable=True),
    sa.Column('level_3', sa.Text(), nullable=True),
    sa.Column('level_2', sa.Text(), nullable=True),
    sa.Column('level_1', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['bank_item_id'], ['rubric_bank_item.id'], ),
    sa.ForeignKeyConstraint(['manual_id'], ['project_manual.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weekly_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manual_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sessions_per_week', sa.Integer(), nullable=True),
    sa.Column('start_week', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manual_id'], ['project_manual.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_plan')
    op.drop_table('manual_rubric')
    op.drop_table('project_manual')
    # ### end Alembic commands ###
